"""empty message

Revision ID: 3d60fd1edeca
Revises: 
Create Date: 2019-04-04 16:57:25.749000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d60fd1edeca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=420), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('client', sa.String(length=10), nullable=True),
    sa.Column('clientPriority', sa.Integer(), nullable=True),
    sa.Column('targetDate', sa.Date(), nullable=True),
    sa.Column('productArea', sa.String(length=42), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
